sudo: required
services:
  - docker

before_install:
  - docker build -t majonathant/docker-react -f Dockerfile.dev .

script:
  - docker run majonathant/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: "docker-react-dev"
  env: "Dockerreactdev-env"
  bucket: "elasticbeanstalk-us-east-2-714392463495"
  bucket_path: "docker-react-dev"
