sudo: required
services:
  - docker

before_install:
  - docker compose build -t majonathant/docker-react -f Dockerfile.dev .

script:
  - docker compose run -e CI=true majonathant/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: "docker-react-dev"
  env: "Dockerreactdev-env"
  bucket: "elasticbeanstalk-us-east-2-714392463495"
  bucket_path: "docker-react-dev"
  on:
    branch: master
