sudo: required
services:
  - docker

before_install:
  - docker-compose build

script:
  - docker-compose run -e CI=true web npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: "docker-react-dev"
  env: "Dockerreactdev-env"
  bucket: "elasticbeanstalk-us-east-2-714392463495"
  bucket_path: "docker-react-dev"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
